version: '3'
services:
  
  #PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${DOCKER_PREFIX}-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #node
  node:
    image: node:15
    container_name: "${DOCKER_PREFIX}-node"
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.15
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    command:
      --default-authentication-plugin=mysql_native_password
      --performance-schema --secure-file-priv=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network      

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-server"
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
      #- /etc/letsencrypt:/etc/letsencrypt/live/laravel.loc/
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: "${DOCKER_PREFIX}-adminer"
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

